// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  cancelSubscription,
  createFeature,
  createPlan,
  createSubscription,
  createUsage,
  createUser,
  getAllTransactions,
  getAllUsers,
  getFeatures,
  getHome,
  getMySubscriptions,
  getMyTransactions,
  getPlans,
  getSubscriptionsByUser,
  getSubscriptionUsage,
  getUserUsage,
  loginUser,
  type Options,
  runBillingCycle,
  updateSubscription,
  uploadFile,
} from "../sdk.gen";
import type {
  CancelSubscriptionData,
  CancelSubscriptionError,
  CancelSubscriptionResponse,
  CreateFeatureData,
  CreateFeatureError,
  CreateFeatureResponse,
  CreatePlanData,
  CreatePlanError,
  CreatePlanResponse,
  CreateSubscriptionData,
  CreateSubscriptionError,
  CreateSubscriptionResponse,
  CreateUsageData,
  CreateUsageError,
  CreateUsageResponse,
  CreateUserData,
  CreateUserError,
  CreateUserResponse,
  GetAllTransactionsData,
  GetAllTransactionsError,
  GetAllTransactionsResponse,
  GetAllUsersData,
  GetAllUsersError,
  GetAllUsersResponse,
  GetFeaturesData,
  GetFeaturesResponse,
  GetHomeData,
  GetMySubscriptionsData,
  GetMySubscriptionsResponse,
  GetMyTransactionsData,
  GetMyTransactionsError,
  GetMyTransactionsResponse,
  GetPlansData,
  GetPlansResponse,
  GetSubscriptionsByUserData,
  GetSubscriptionsByUserError,
  GetSubscriptionsByUserResponse,
  GetSubscriptionUsageData,
  GetSubscriptionUsageError,
  GetSubscriptionUsageResponse,
  GetUserUsageData,
  GetUserUsageError,
  GetUserUsageResponse,
  LoginUserData,
  LoginUserError,
  LoginUserResponse,
  RunBillingCycleData,
  RunBillingCycleResponse,
  UpdateSubscriptionData,
  UpdateSubscriptionError,
  UpdateSubscriptionResponse,
  UploadFileData,
  UploadFileError,
  UploadFileResponse,
} from "../types.gen";

/**
 * Create User
 */
export const createUserMutation = (
  options?: Partial<Options<CreateUserData>>,
): UseMutationOptions<
  CreateUserResponse,
  CreateUserError,
  Options<CreateUserData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateUserResponse,
    CreateUserError,
    Options<CreateUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Login
 */
export const loginUserMutation = (
  options?: Partial<Options<LoginUserData>>,
): UseMutationOptions<
  LoginUserResponse,
  LoginUserError,
  Options<LoginUserData>
> => {
  const mutationOptions: UseMutationOptions<
    LoginUserResponse,
    LoginUserError,
    Options<LoginUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await loginUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getAllUsersQueryKey = (options?: Options<GetAllUsersData>) =>
  createQueryKey("getAllUsers", options);

/**
 * Get all users
 */
export const getAllUsersOptions = (options?: Options<GetAllUsersData>) =>
  queryOptions<
    GetAllUsersResponse,
    GetAllUsersError,
    GetAllUsersResponse,
    ReturnType<typeof getAllUsersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAllUsers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAllUsersQueryKey(options),
  });

/**
 * Upload File
 */
export const uploadFileMutation = (
  options?: Partial<Options<UploadFileData>>,
): UseMutationOptions<
  UploadFileResponse,
  UploadFileError,
  Options<UploadFileData>
> => {
  const mutationOptions: UseMutationOptions<
    UploadFileResponse,
    UploadFileError,
    Options<UploadFileData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await uploadFile({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getFeaturesQueryKey = (options?: Options<GetFeaturesData>) =>
  createQueryKey("getFeatures", options);

/**
 * Get Features
 */
export const getFeaturesOptions = (options?: Options<GetFeaturesData>) =>
  queryOptions<
    GetFeaturesResponse,
    DefaultError,
    GetFeaturesResponse,
    ReturnType<typeof getFeaturesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getFeatures({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getFeaturesQueryKey(options),
  });

/**
 * Create Feature
 */
export const createFeatureMutation = (
  options?: Partial<Options<CreateFeatureData>>,
): UseMutationOptions<
  CreateFeatureResponse,
  CreateFeatureError,
  Options<CreateFeatureData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateFeatureResponse,
    CreateFeatureError,
    Options<CreateFeatureData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createFeature({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getPlansQueryKey = (options?: Options<GetPlansData>) =>
  createQueryKey("getPlans", options);

/**
 * Get All Plans
 */
export const getPlansOptions = (options?: Options<GetPlansData>) =>
  queryOptions<
    GetPlansResponse,
    DefaultError,
    GetPlansResponse,
    ReturnType<typeof getPlansQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPlans({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getPlansQueryKey(options),
  });

/**
 * Create Plan
 */
export const createPlanMutation = (
  options?: Partial<Options<CreatePlanData>>,
): UseMutationOptions<
  CreatePlanResponse,
  CreatePlanError,
  Options<CreatePlanData>
> => {
  const mutationOptions: UseMutationOptions<
    CreatePlanResponse,
    CreatePlanError,
    Options<CreatePlanData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createPlan({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getMyTransactionsQueryKey = (
  options?: Options<GetMyTransactionsData>,
) => createQueryKey("getMyTransactions", options);

/**
 * Get current user's transaction & payment history
 */
export const getMyTransactionsOptions = (
  options?: Options<GetMyTransactionsData>,
) =>
  queryOptions<
    GetMyTransactionsResponse,
    GetMyTransactionsError,
    GetMyTransactionsResponse,
    ReturnType<typeof getMyTransactionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMyTransactions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMyTransactionsQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const getMyTransactionsInfiniteQueryKey = (
  options?: Options<GetMyTransactionsData>,
): QueryKey<Options<GetMyTransactionsData>> =>
  createQueryKey("getMyTransactions", options, true);

/**
 * Get current user's transaction & payment history
 */
export const getMyTransactionsInfiniteOptions = (
  options?: Options<GetMyTransactionsData>,
) => {
  const opts = infiniteQueryOptions<
    GetMyTransactionsResponse,
    GetMyTransactionsError,
    InfiniteData<GetMyTransactionsResponse>,
    QueryKey<Options<GetMyTransactionsData>>,
    | number
    | null
    | Pick<
        QueryKey<Options<GetMyTransactionsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetMyTransactionsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getMyTransactions({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getMyTransactionsInfiniteQueryKey(options),
    },
  );
  return opts as Omit<typeof opts, "initialData">;
};

export const getAllTransactionsQueryKey = (
  options?: Options<GetAllTransactionsData>,
) => createQueryKey("getAllTransactions", options);

/**
 * Get all transactions (Admin view)
 */
export const getAllTransactionsOptions = (
  options?: Options<GetAllTransactionsData>,
) =>
  queryOptions<
    GetAllTransactionsResponse,
    GetAllTransactionsError,
    GetAllTransactionsResponse,
    ReturnType<typeof getAllTransactionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAllTransactions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAllTransactionsQueryKey(options),
  });

export const getAllTransactionsInfiniteQueryKey = (
  options?: Options<GetAllTransactionsData>,
): QueryKey<Options<GetAllTransactionsData>> =>
  createQueryKey("getAllTransactions", options, true);

/**
 * Get all transactions (Admin view)
 */
export const getAllTransactionsInfiniteOptions = (
  options?: Options<GetAllTransactionsData>,
) => {
  const opts = infiniteQueryOptions<
    GetAllTransactionsResponse,
    GetAllTransactionsError,
    InfiniteData<GetAllTransactionsResponse>,
    QueryKey<Options<GetAllTransactionsData>>,
    | number
    | null
    | Pick<
        QueryKey<Options<GetAllTransactionsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetAllTransactionsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getAllTransactions({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getAllTransactionsInfiniteQueryKey(options),
    },
  );
  return opts as Omit<typeof opts, "initialData">;
};

/**
 * Create Subscription
 */
export const createSubscriptionMutation = (
  options?: Partial<Options<CreateSubscriptionData>>,
): UseMutationOptions<
  CreateSubscriptionResponse,
  CreateSubscriptionError,
  Options<CreateSubscriptionData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateSubscriptionResponse,
    CreateSubscriptionError,
    Options<CreateSubscriptionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createSubscription({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getSubscriptionUsageQueryKey = (
  options: Options<GetSubscriptionUsageData>,
) => createQueryKey("getSubscriptionUsage", options);

/**
 * Get usage history for a subscription
 */
export const getSubscriptionUsageOptions = (
  options: Options<GetSubscriptionUsageData>,
) =>
  queryOptions<
    GetSubscriptionUsageResponse,
    GetSubscriptionUsageError,
    GetSubscriptionUsageResponse,
    ReturnType<typeof getSubscriptionUsageQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSubscriptionUsage({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSubscriptionUsageQueryKey(options),
  });

/**
 * Cancel / Deactivate a subscription
 */
export const cancelSubscriptionMutation = (
  options?: Partial<Options<CancelSubscriptionData>>,
): UseMutationOptions<
  CancelSubscriptionResponse,
  CancelSubscriptionError,
  Options<CancelSubscriptionData>
> => {
  const mutationOptions: UseMutationOptions<
    CancelSubscriptionResponse,
    CancelSubscriptionError,
    Options<CancelSubscriptionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await cancelSubscription({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Change plan for an active subscription
 */
export const updateSubscriptionMutation = (
  options?: Partial<Options<UpdateSubscriptionData>>,
): UseMutationOptions<
  UpdateSubscriptionResponse,
  UpdateSubscriptionError,
  Options<UpdateSubscriptionData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateSubscriptionResponse,
    UpdateSubscriptionError,
    Options<UpdateSubscriptionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateSubscription({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getMySubscriptionsQueryKey = (
  options?: Options<GetMySubscriptionsData>,
) => createQueryKey("getMySubscriptions", options);

/**
 * Get current user's subscriptions
 */
export const getMySubscriptionsOptions = (
  options?: Options<GetMySubscriptionsData>,
) =>
  queryOptions<
    GetMySubscriptionsResponse,
    DefaultError,
    GetMySubscriptionsResponse,
    ReturnType<typeof getMySubscriptionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMySubscriptions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMySubscriptionsQueryKey(options),
  });

export const getSubscriptionsByUserQueryKey = (
  options: Options<GetSubscriptionsByUserData>,
) => createQueryKey("getSubscriptionsByUser", options);

/**
 * Get subscriptions by user ID (Admin)
 */
export const getSubscriptionsByUserOptions = (
  options: Options<GetSubscriptionsByUserData>,
) =>
  queryOptions<
    GetSubscriptionsByUserResponse,
    GetSubscriptionsByUserError,
    GetSubscriptionsByUserResponse,
    ReturnType<typeof getSubscriptionsByUserQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSubscriptionsByUser({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSubscriptionsByUserQueryKey(options),
  });

/**
 * Record usage for a subscription feature (Admin only)
 */
export const createUsageMutation = (
  options?: Partial<Options<CreateUsageData>>,
): UseMutationOptions<
  CreateUsageResponse,
  CreateUsageError,
  Options<CreateUsageData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateUsageResponse,
    CreateUsageError,
    Options<CreateUsageData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createUsage({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getUserUsageQueryKey = (options: Options<GetUserUsageData>) =>
  createQueryKey("getUserUsage", options);

/**
 * Get all usage records for a specific user
 */
export const getUserUsageOptions = (options: Options<GetUserUsageData>) =>
  queryOptions<
    GetUserUsageResponse,
    GetUserUsageError,
    GetUserUsageResponse,
    ReturnType<typeof getUserUsageQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUserUsage({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUserUsageQueryKey(options),
  });

/**
 * Launch the call to charge accounts on billing_day
 */
export const runBillingCycleMutation = (
  options?: Partial<Options<RunBillingCycleData>>,
): UseMutationOptions<
  RunBillingCycleResponse,
  DefaultError,
  Options<RunBillingCycleData>
> => {
  const mutationOptions: UseMutationOptions<
    RunBillingCycleResponse,
    DefaultError,
    Options<RunBillingCycleData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await runBillingCycle({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getHomeQueryKey = (options?: Options<GetHomeData>) =>
  createQueryKey("getHome", options);

/**
 * Home
 */
export const getHomeOptions = (options?: Options<GetHomeData>) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof getHomeQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getHome({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getHomeQueryKey(options),
  });
