// This file is auto-generated by @hey-api/openapi-ts

export const APIResponse_CursorPaginatedTransactions_Schema = {
  properties: {
    success: {
      type: "boolean",
      title: "Success",
      default: true,
    },
    status_code: {
      type: "integer",
      title: "Status Code",
      default: 200,
      examples: [200],
    },
    message: {
      type: "string",
      title: "Message",
      default: "Operation completed successfully",
    },
    data: {
      anyOf: [
        {
          $ref: "#/components/schemas/CursorPaginatedTransactions",
        },
        {
          type: "null",
        },
      ],
    },
  },
  type: "object",
  title: "APIResponse[CursorPaginatedTransactions]",
} as const;

export const APIResponse_FeatureResponse_Schema = {
  properties: {
    success: {
      type: "boolean",
      title: "Success",
      default: true,
    },
    status_code: {
      type: "integer",
      title: "Status Code",
      default: 200,
      examples: [200],
    },
    message: {
      type: "string",
      title: "Message",
      default: "Operation completed successfully",
    },
    data: {
      anyOf: [
        {
          $ref: "#/components/schemas/FeatureResponse",
        },
        {
          type: "null",
        },
      ],
    },
  },
  type: "object",
  title: "APIResponse[FeatureResponse]",
} as const;

export const APIResponse_PlanResponse_Schema = {
  properties: {
    success: {
      type: "boolean",
      title: "Success",
      default: true,
    },
    status_code: {
      type: "integer",
      title: "Status Code",
      default: 200,
      examples: [200],
    },
    message: {
      type: "string",
      title: "Message",
      default: "Operation completed successfully",
    },
    data: {
      anyOf: [
        {
          $ref: "#/components/schemas/PlanResponse",
        },
        {
          type: "null",
        },
      ],
    },
  },
  type: "object",
  title: "APIResponse[PlanResponse]",
} as const;

export const APIResponse_SubscriptionResponse_Schema = {
  properties: {
    success: {
      type: "boolean",
      title: "Success",
      default: true,
    },
    status_code: {
      type: "integer",
      title: "Status Code",
      default: 200,
      examples: [200],
    },
    message: {
      type: "string",
      title: "Message",
      default: "Operation completed successfully",
    },
    data: {
      anyOf: [
        {
          $ref: "#/components/schemas/SubscriptionResponse",
        },
        {
          type: "null",
        },
      ],
    },
  },
  type: "object",
  title: "APIResponse[SubscriptionResponse]",
} as const;

export const APIResponse_UsageResponse_Schema = {
  properties: {
    success: {
      type: "boolean",
      title: "Success",
      default: true,
    },
    status_code: {
      type: "integer",
      title: "Status Code",
      default: 200,
      examples: [200],
    },
    message: {
      type: "string",
      title: "Message",
      default: "Operation completed successfully",
    },
    data: {
      anyOf: [
        {
          $ref: "#/components/schemas/UsageResponse",
        },
        {
          type: "null",
        },
      ],
    },
  },
  type: "object",
  title: "APIResponse[UsageResponse]",
} as const;

export const APIResponse_dict_Schema = {
  properties: {
    success: {
      type: "boolean",
      title: "Success",
      default: true,
    },
    status_code: {
      type: "integer",
      title: "Status Code",
      default: 200,
      examples: [200],
    },
    message: {
      type: "string",
      title: "Message",
      default: "Operation completed successfully",
    },
    data: {
      anyOf: [
        {
          additionalProperties: true,
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Data",
    },
  },
  type: "object",
  title: "APIResponse[dict]",
} as const;

export const APIResponse_list_FeatureResponse__Schema = {
  properties: {
    success: {
      type: "boolean",
      title: "Success",
      default: true,
    },
    status_code: {
      type: "integer",
      title: "Status Code",
      default: 200,
      examples: [200],
    },
    message: {
      type: "string",
      title: "Message",
      default: "Operation completed successfully",
    },
    data: {
      anyOf: [
        {
          items: {
            $ref: "#/components/schemas/FeatureResponse",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Data",
    },
  },
  type: "object",
  title: "APIResponse[list[FeatureResponse]]",
} as const;

export const APIResponse_list_PlanResponse__Schema = {
  properties: {
    success: {
      type: "boolean",
      title: "Success",
      default: true,
    },
    status_code: {
      type: "integer",
      title: "Status Code",
      default: 200,
      examples: [200],
    },
    message: {
      type: "string",
      title: "Message",
      default: "Operation completed successfully",
    },
    data: {
      anyOf: [
        {
          items: {
            $ref: "#/components/schemas/PlanResponse",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Data",
    },
  },
  type: "object",
  title: "APIResponse[list[PlanResponse]]",
} as const;

export const APIResponse_list_SubscriptionResponse__Schema = {
  properties: {
    success: {
      type: "boolean",
      title: "Success",
      default: true,
    },
    status_code: {
      type: "integer",
      title: "Status Code",
      default: 200,
      examples: [200],
    },
    message: {
      type: "string",
      title: "Message",
      default: "Operation completed successfully",
    },
    data: {
      anyOf: [
        {
          items: {
            $ref: "#/components/schemas/SubscriptionResponse",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Data",
    },
  },
  type: "object",
  title: "APIResponse[list[SubscriptionResponse]]",
} as const;

export const APIResponse_list_UsageResponse__Schema = {
  properties: {
    success: {
      type: "boolean",
      title: "Success",
      default: true,
    },
    status_code: {
      type: "integer",
      title: "Status Code",
      default: 200,
      examples: [200],
    },
    message: {
      type: "string",
      title: "Message",
      default: "Operation completed successfully",
    },
    data: {
      anyOf: [
        {
          items: {
            $ref: "#/components/schemas/UsageResponse",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Data",
    },
  },
  type: "object",
  title: "APIResponse[list[UsageResponse]]",
} as const;

export const APIResponse_list_UserResponse__Schema = {
  properties: {
    success: {
      type: "boolean",
      title: "Success",
      default: true,
    },
    status_code: {
      type: "integer",
      title: "Status Code",
      default: 200,
      examples: [200],
    },
    message: {
      type: "string",
      title: "Message",
      default: "Operation completed successfully",
    },
    data: {
      anyOf: [
        {
          items: {
            $ref: "#/components/schemas/UserResponse",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Data",
    },
  },
  type: "object",
  title: "APIResponse[list[UserResponse]]",
} as const;

export const Body_upload_fileSchema = {
  properties: {
    file: {
      type: "string",
      contentMediaType: "application/octet-stream",
      title: "File",
    },
  },
  type: "object",
  required: ["file"],
  title: "Body_upload_file",
} as const;

export const CursorPaginatedTransactionsSchema = {
  properties: {
    items: {
      items: {
        $ref: "#/components/schemas/TransactionResponse",
      },
      type: "array",
      title: "Items",
    },
    next_cursor: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Next Cursor",
    },
    has_more: {
      type: "boolean",
      title: "Has More",
    },
  },
  type: "object",
  required: ["items", "has_more"],
  title: "CursorPaginatedTransactions",
} as const;

export const FeatureCreateSchema = {
  properties: {
    name: {
      type: "string",
      maxLength: 255,
      minLength: 2,
      title: "Name",
      examples: ["API Calls"],
    },
    code: {
      type: "string",
      maxLength: 100,
      minLength: 2,
      title: "Code",
      examples: ["api_calls"],
    },
    unit_price: {
      anyOf: [
        {
          type: "number",
          exclusiveMinimum: 0,
        },
        {
          type: "string",
          pattern: "^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$",
        },
      ],
      title: "Unit Price",
      examples: [0.05],
    },
    max_unit_limit: {
      type: "integer",
      exclusiveMinimum: 0,
      title: "Max Unit Limit",
      examples: [1000],
    },
    is_active: {
      type: "boolean",
      title: "Is Active",
      default: true,
    },
  },
  type: "object",
  required: ["name", "code", "unit_price", "max_unit_limit"],
  title: "FeatureCreate",
} as const;

export const FeatureResponseSchema = {
  properties: {
    name: {
      type: "string",
      maxLength: 255,
      minLength: 2,
      title: "Name",
      examples: ["API Calls"],
    },
    code: {
      type: "string",
      maxLength: 100,
      minLength: 2,
      title: "Code",
      examples: ["api_calls"],
    },
    unit_price: {
      type: "string",
      pattern: "^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$",
      title: "Unit Price",
      examples: [0.05],
    },
    max_unit_limit: {
      type: "integer",
      exclusiveMinimum: 0,
      title: "Max Unit Limit",
      examples: [1000],
    },
    is_active: {
      type: "boolean",
      title: "Is Active",
      default: true,
    },
    id: {
      type: "integer",
      title: "Id",
    },
  },
  type: "object",
  required: ["name", "code", "unit_price", "max_unit_limit", "id"],
  title: "FeatureResponse",
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const PlanCreateSchema = {
  properties: {
    name: {
      type: "string",
      maxLength: 50,
      minLength: 3,
      title: "Name",
      examples: ["Pro Plan"],
    },
    monthly_fee: {
      type: "number",
      minimum: 0,
      title: "Monthly Fee",
      description: "The recurring monthly price charged for this plan",
      examples: [49.99],
    },
    feature_ids: {
      items: {
        type: "integer",
      },
      type: "array",
      title: "Feature Ids",
      description: "List of feature IDs associated with this plan",
      examples: [[1, 2, 3]],
    },
  },
  type: "object",
  required: ["name", "monthly_fee"],
  title: "PlanCreate",
} as const;

export const PlanResponseSchema = {
  properties: {
    name: {
      type: "string",
      maxLength: 50,
      minLength: 3,
      title: "Name",
      examples: ["Pro Plan"],
    },
    monthly_fee: {
      type: "number",
      minimum: 0,
      title: "Monthly Fee",
      description: "The recurring monthly price charged for this plan",
      examples: [49.99],
    },
    id: {
      type: "integer",
      title: "Id",
    },
    features: {
      items: {
        $ref: "#/components/schemas/FeatureResponse",
      },
      type: "array",
      title: "Features",
    },
  },
  type: "object",
  required: ["name", "monthly_fee", "id"],
  title: "PlanResponse",
} as const;

export const SubscriptionCreateSchema = {
  properties: {
    plan_id: {
      type: "integer",
      title: "Plan Id",
      description: "ID of the plan to subscribe to",
    },
  },
  type: "object",
  required: ["plan_id"],
  title: "SubscriptionCreate",
} as const;

export const SubscriptionResponseSchema = {
  properties: {
    id: {
      type: "integer",
      title: "Id",
    },
    user_id: {
      type: "integer",
      title: "User Id",
    },
    plan_id: {
      type: "integer",
      title: "Plan Id",
    },
    billing_day: {
      type: "integer",
      title: "Billing Day",
    },
    last_billing_date: {
      anyOf: [
        {
          type: "string",
          format: "date",
        },
        {
          type: "null",
        },
      ],
      title: "Last Billing Date",
    },
    is_active: {
      type: "boolean",
      title: "Is Active",
    },
    plan: {
      $ref: "#/components/schemas/PlanResponse",
    },
  },
  type: "object",
  required: ["id", "user_id", "plan_id", "billing_day", "is_active", "plan"],
  title: "SubscriptionResponse",
} as const;

export const SubscriptionUpdateSchema = {
  properties: {
    plan_id: {
      type: "integer",
      title: "Plan Id",
      description: "Change subscription to a new plan ID",
    },
    billing_day: {
      anyOf: [
        {
          type: "integer",
          maximum: 28,
          minimum: 1,
        },
        {
          type: "null",
        },
      ],
      title: "Billing Day",
      description: "Update recurring billing day (1-28)",
      examples: [1],
    },
    last_billing_date: {
      anyOf: [
        {
          type: "string",
          format: "date",
        },
        {
          type: "null",
        },
      ],
      title: "Last Billing Date",
    },
  },
  type: "object",
  required: ["plan_id"],
  title: "SubscriptionUpdate",
} as const;

export const TokenSchema = {
  properties: {
    access_token: {
      type: "string",
      title: "Access Token",
    },
    token_type: {
      type: "string",
      title: "Token Type",
      default: "bearer",
    },
  },
  type: "object",
  required: ["access_token"],
  title: "Token",
} as const;

export const TokenResponseSchema = {
  properties: {
    token: {
      $ref: "#/components/schemas/Token",
    },
    user: {
      $ref: "#/components/schemas/UserResponse",
    },
  },
  type: "object",
  required: ["token", "user"],
  title: "TokenResponse",
} as const;

export const TransactionResponseSchema = {
  properties: {
    id: {
      type: "integer",
      title: "Id",
    },
    user_id: {
      type: "integer",
      title: "User Id",
    },
    subscription_id: {
      type: "integer",
      title: "Subscription Id",
    },
    base_price: {
      type: "string",
      pattern: "^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$",
      title: "Base Price",
    },
    extra_charges: {
      type: "string",
      pattern: "^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$",
      title: "Extra Charges",
    },
    is_recurring: {
      type: "boolean",
      title: "Is Recurring",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
    },
    total_amount: {
      type: "string",
      pattern: "^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$",
      title: "Total Amount",
      readOnly: true,
    },
  },
  type: "object",
  required: [
    "id",
    "user_id",
    "subscription_id",
    "base_price",
    "extra_charges",
    "is_recurring",
    "created_at",
    "total_amount",
  ],
  title: "TransactionResponse",
} as const;

export const UploadResponseSchema = {
  properties: {
    url: {
      type: "string",
      title: "Url",
    },
  },
  type: "object",
  required: ["url"],
  title: "UploadResponse",
} as const;

export const UsageCreateSchema = {
  properties: {
    subscription_id: {
      type: "integer",
      title: "Subscription Id",
      description: "ID of the active subscription being used",
    },
    feature_id: {
      type: "integer",
      title: "Feature Id",
      description: "ID of the feature feature being consumed",
    },
    units_used: {
      type: "integer",
      exclusiveMinimum: 0,
      title: "Units Used",
      description: "Number of units consumed (must be greater than 0)",
      examples: [5],
    },
  },
  type: "object",
  required: ["subscription_id", "feature_id", "units_used"],
  title: "UsageCreate",
} as const;

export const UsageResponseSchema = {
  properties: {
    id: {
      type: "integer",
      title: "Id",
    },
    subscription_id: {
      type: "integer",
      title: "Subscription Id",
    },
    feature_id: {
      type: "integer",
      title: "Feature Id",
    },
    units_used: {
      type: "integer",
      title: "Units Used",
    },
    feature: {
      anyOf: [
        {
          $ref: "#/components/schemas/FeatureResponse",
        },
        {
          type: "null",
        },
      ],
    },
  },
  type: "object",
  required: ["id", "subscription_id", "feature_id", "units_used"],
  title: "UsageResponse",
} as const;

export const UserCreateSchema = {
  properties: {
    name: {
      type: "string",
      maxLength: 20,
      minLength: 3,
      title: "Name",
    },
    email: {
      type: "string",
      format: "email",
      title: "Email",
    },
    role: {
      $ref: "#/components/schemas/UserRole",
      default: "buyer",
    },
    password: {
      type: "string",
      minLength: 5,
      title: "Password",
    },
    profile_img: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Profile Img",
    },
  },
  type: "object",
  required: ["name", "email", "password"],
  title: "UserCreate",
} as const;

export const UserLoginSchema = {
  properties: {
    email: {
      type: "string",
      format: "email",
      title: "Email",
    },
    password: {
      type: "string",
      minLength: 5,
      title: "Password",
    },
  },
  type: "object",
  required: ["email", "password"],
  title: "UserLogin",
} as const;

export const UserResponseSchema = {
  properties: {
    name: {
      type: "string",
      maxLength: 20,
      minLength: 3,
      title: "Name",
    },
    email: {
      type: "string",
      format: "email",
      title: "Email",
    },
    role: {
      $ref: "#/components/schemas/UserRole",
      default: "buyer",
    },
    id: {
      type: "integer",
      title: "Id",
    },
    profile_img: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Profile Img",
    },
  },
  type: "object",
  required: ["name", "email", "id"],
  title: "UserResponse",
} as const;

export const UserRoleSchema = {
  type: "string",
  enum: ["admin", "buyer"],
  title: "UserRole",
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
    input: {
      title: "Input",
    },
    ctx: {
      type: "object",
      title: "Context",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;

export const APIResponse_CursorPaginatedTransactions_WritableSchema = {
  properties: {
    success: {
      type: "boolean",
      title: "Success",
      default: true,
    },
    status_code: {
      type: "integer",
      title: "Status Code",
      default: 200,
      examples: [200],
    },
    message: {
      type: "string",
      title: "Message",
      default: "Operation completed successfully",
    },
    data: {
      anyOf: [
        {
          $ref: "#/components/schemas/CursorPaginatedTransactionsWritable",
        },
        {
          type: "null",
        },
      ],
    },
  },
  type: "object",
  title: "APIResponse[CursorPaginatedTransactions]",
} as const;

export const CursorPaginatedTransactionsWritableSchema = {
  properties: {
    items: {
      items: {
        $ref: "#/components/schemas/TransactionResponseWritable",
      },
      type: "array",
      title: "Items",
    },
    next_cursor: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Next Cursor",
    },
    has_more: {
      type: "boolean",
      title: "Has More",
    },
  },
  type: "object",
  required: ["items", "has_more"],
  title: "CursorPaginatedTransactions",
} as const;

export const TransactionResponseWritableSchema = {
  properties: {
    id: {
      type: "integer",
      title: "Id",
    },
    user_id: {
      type: "integer",
      title: "User Id",
    },
    subscription_id: {
      type: "integer",
      title: "Subscription Id",
    },
    base_price: {
      type: "string",
      pattern: "^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$",
      title: "Base Price",
    },
    extra_charges: {
      type: "string",
      pattern: "^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$",
      title: "Extra Charges",
    },
    is_recurring: {
      type: "boolean",
      title: "Is Recurring",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
    },
  },
  type: "object",
  required: [
    "id",
    "user_id",
    "subscription_id",
    "base_price",
    "extra_charges",
    "is_recurring",
    "created_at",
  ],
  title: "TransactionResponse",
} as const;
