// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type ClientMeta,
  formDataBodySerializer,
  type Options as Options2,
  type RequestResult,
  type TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  CancelSubscriptionData,
  CancelSubscriptionErrors,
  CancelSubscriptionResponses,
  CreateFeatureData,
  CreateFeatureErrors,
  CreateFeatureResponses,
  CreatePlanData,
  CreatePlanErrors,
  CreatePlanResponses,
  CreateSubscriptionData,
  CreateSubscriptionErrors,
  CreateSubscriptionResponses,
  CreateUsageData,
  CreateUsageErrors,
  CreateUsageResponses,
  CreateUserData,
  CreateUserErrors,
  CreateUserResponses,
  GetAllTransactionsData,
  GetAllTransactionsErrors,
  GetAllTransactionsResponses,
  GetAllUsersData,
  GetAllUsersErrors,
  GetAllUsersResponses,
  GetFeaturesData,
  GetFeaturesResponses,
  GetHomeData,
  GetHomeResponses,
  GetMySubscriptionsData,
  GetMySubscriptionsResponses,
  GetMyTransactionsData,
  GetMyTransactionsErrors,
  GetMyTransactionsResponses,
  GetPlansData,
  GetPlansResponses,
  GetSubscriptionsByUserData,
  GetSubscriptionsByUserErrors,
  GetSubscriptionsByUserResponses,
  GetSubscriptionUsageData,
  GetSubscriptionUsageErrors,
  GetSubscriptionUsageResponses,
  GetUserUsageData,
  GetUserUsageErrors,
  GetUserUsageResponses,
  LoginUserData,
  LoginUserErrors,
  LoginUserResponses,
  RunBillingCycleData,
  RunBillingCycleResponses,
  UpdateSubscriptionData,
  UpdateSubscriptionErrors,
  UpdateSubscriptionResponses,
  UploadFileData,
  UploadFileErrors,
  UploadFileResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Create User
 */
export const createUser = <ThrowOnError extends boolean = false>(
  options: Options<CreateUserData, ThrowOnError>,
): RequestResult<CreateUserResponses, CreateUserErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateUserResponses,
    CreateUserErrors,
    ThrowOnError
  >({
    url: "/api/v1/users/create",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Login
 */
export const loginUser = <ThrowOnError extends boolean = false>(
  options: Options<LoginUserData, ThrowOnError>,
): RequestResult<LoginUserResponses, LoginUserErrors, ThrowOnError> =>
  (options.client ?? client).post<
    LoginUserResponses,
    LoginUserErrors,
    ThrowOnError
  >({
    url: "/api/v1/users/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get all users
 */
export const getAllUsers = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllUsersData, ThrowOnError>,
): RequestResult<GetAllUsersResponses, GetAllUsersErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetAllUsersResponses,
    GetAllUsersErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/",
    ...options,
  });

/**
 * Upload File
 */
export const uploadFile = <ThrowOnError extends boolean = false>(
  options: Options<UploadFileData, ThrowOnError>,
): RequestResult<UploadFileResponses, UploadFileErrors, ThrowOnError> =>
  (options.client ?? client).post<
    UploadFileResponses,
    UploadFileErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    url: "/api/v1/storage/upload",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });

/**
 * Get Features
 */
export const getFeatures = <ThrowOnError extends boolean = false>(
  options?: Options<GetFeaturesData, ThrowOnError>,
): RequestResult<GetFeaturesResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetFeaturesResponses, unknown, ThrowOnError>({
    url: "/api/v1/features/",
    ...options,
  });

/**
 * Create Feature
 */
export const createFeature = <ThrowOnError extends boolean = false>(
  options: Options<CreateFeatureData, ThrowOnError>,
): RequestResult<CreateFeatureResponses, CreateFeatureErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateFeatureResponses,
    CreateFeatureErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/features/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get All Plans
 */
export const getPlans = <ThrowOnError extends boolean = false>(
  options?: Options<GetPlansData, ThrowOnError>,
): RequestResult<GetPlansResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetPlansResponses, unknown, ThrowOnError>({
    url: "/api/v1/plans/",
    ...options,
  });

/**
 * Create Plan
 */
export const createPlan = <ThrowOnError extends boolean = false>(
  options: Options<CreatePlanData, ThrowOnError>,
): RequestResult<CreatePlanResponses, CreatePlanErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreatePlanResponses,
    CreatePlanErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/plans/create",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get current user's transaction & payment history
 */
export const getMyTransactions = <ThrowOnError extends boolean = false>(
  options?: Options<GetMyTransactionsData, ThrowOnError>,
): RequestResult<
  GetMyTransactionsResponses,
  GetMyTransactionsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetMyTransactionsResponses,
    GetMyTransactionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/transaction/me",
    ...options,
  });

/**
 * Get all transactions (Admin view)
 */
export const getAllTransactions = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllTransactionsData, ThrowOnError>,
): RequestResult<
  GetAllTransactionsResponses,
  GetAllTransactionsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetAllTransactionsResponses,
    GetAllTransactionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/transaction/",
    ...options,
  });

/**
 * Create Subscription
 */
export const createSubscription = <ThrowOnError extends boolean = false>(
  options: Options<CreateSubscriptionData, ThrowOnError>,
): RequestResult<
  CreateSubscriptionResponses,
  CreateSubscriptionErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateSubscriptionResponses,
    CreateSubscriptionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/subscription/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get usage history for a subscription
 */
export const getSubscriptionUsage = <ThrowOnError extends boolean = false>(
  options: Options<GetSubscriptionUsageData, ThrowOnError>,
): RequestResult<
  GetSubscriptionUsageResponses,
  GetSubscriptionUsageErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetSubscriptionUsageResponses,
    GetSubscriptionUsageErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/subscription/{subscription_id}/usage",
    ...options,
  });

/**
 * Cancel / Deactivate a subscription
 */
export const cancelSubscription = <ThrowOnError extends boolean = false>(
  options: Options<CancelSubscriptionData, ThrowOnError>,
): RequestResult<
  CancelSubscriptionResponses,
  CancelSubscriptionErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    CancelSubscriptionResponses,
    CancelSubscriptionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/subscription/{subscription_id}",
    ...options,
  });

/**
 * Change plan for an active subscription
 */
export const updateSubscription = <ThrowOnError extends boolean = false>(
  options: Options<UpdateSubscriptionData, ThrowOnError>,
): RequestResult<
  UpdateSubscriptionResponses,
  UpdateSubscriptionErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    UpdateSubscriptionResponses,
    UpdateSubscriptionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/subscription/{subscription_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get current user's subscriptions
 */
export const getMySubscriptions = <ThrowOnError extends boolean = false>(
  options?: Options<GetMySubscriptionsData, ThrowOnError>,
): RequestResult<GetMySubscriptionsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    GetMySubscriptionsResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/subscription/me",
    ...options,
  });

/**
 * Get subscriptions by user ID (Admin)
 */
export const getSubscriptionsByUser = <ThrowOnError extends boolean = false>(
  options: Options<GetSubscriptionsByUserData, ThrowOnError>,
): RequestResult<
  GetSubscriptionsByUserResponses,
  GetSubscriptionsByUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetSubscriptionsByUserResponses,
    GetSubscriptionsByUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/subscription/user/{user_id}",
    ...options,
  });

/**
 * Record usage for a subscription feature (Admin only)
 */
export const createUsage = <ThrowOnError extends boolean = false>(
  options: Options<CreateUsageData, ThrowOnError>,
): RequestResult<CreateUsageResponses, CreateUsageErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateUsageResponses,
    CreateUsageErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/usage/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get all usage records for a specific user
 */
export const getUserUsage = <ThrowOnError extends boolean = false>(
  options: Options<GetUserUsageData, ThrowOnError>,
): RequestResult<GetUserUsageResponses, GetUserUsageErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetUserUsageResponses,
    GetUserUsageErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/usage/user/{user_id}",
    ...options,
  });

/**
 * Launch the call to charge accounts on billing_day
 */
export const runBillingCycle = <ThrowOnError extends boolean = false>(
  options?: Options<RunBillingCycleData, ThrowOnError>,
): RequestResult<RunBillingCycleResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).post<
    RunBillingCycleResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/billing/run",
    ...options,
  });

/**
 * Home
 */
export const getHome = <ThrowOnError extends boolean = false>(
  options?: Options<GetHomeData, ThrowOnError>,
): RequestResult<GetHomeResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetHomeResponses, unknown, ThrowOnError>({
    url: "/",
    ...options,
  });
