// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * APIResponse[CursorPaginatedTransactions]
 */
export type ApiResponseCursorPaginatedTransactions = {
  /**
   * Success
   */
  success?: boolean;
  /**
   * Status Code
   */
  status_code?: number;
  /**
   * Message
   */
  message?: string;
  data?: CursorPaginatedTransactions | null;
};

/**
 * APIResponse[FeatureResponse]
 */
export type ApiResponseFeatureResponse = {
  /**
   * Success
   */
  success?: boolean;
  /**
   * Status Code
   */
  status_code?: number;
  /**
   * Message
   */
  message?: string;
  data?: FeatureResponse | null;
};

/**
 * APIResponse[PlanResponse]
 */
export type ApiResponsePlanResponse = {
  /**
   * Success
   */
  success?: boolean;
  /**
   * Status Code
   */
  status_code?: number;
  /**
   * Message
   */
  message?: string;
  data?: PlanResponse | null;
};

/**
 * APIResponse[SubscriptionResponse]
 */
export type ApiResponseSubscriptionResponse = {
  /**
   * Success
   */
  success?: boolean;
  /**
   * Status Code
   */
  status_code?: number;
  /**
   * Message
   */
  message?: string;
  data?: SubscriptionResponse | null;
};

/**
 * APIResponse[UsageResponse]
 */
export type ApiResponseUsageResponse = {
  /**
   * Success
   */
  success?: boolean;
  /**
   * Status Code
   */
  status_code?: number;
  /**
   * Message
   */
  message?: string;
  data?: UsageResponse | null;
};

/**
 * APIResponse[dict]
 */
export type ApiResponseDict = {
  /**
   * Success
   */
  success?: boolean;
  /**
   * Status Code
   */
  status_code?: number;
  /**
   * Message
   */
  message?: string;
  /**
   * Data
   */
  data?: {
    [key: string]: unknown;
  } | null;
};

/**
 * APIResponse[list[FeatureResponse]]
 */
export type ApiResponseListFeatureResponse = {
  /**
   * Success
   */
  success?: boolean;
  /**
   * Status Code
   */
  status_code?: number;
  /**
   * Message
   */
  message?: string;
  /**
   * Data
   */
  data?: Array<FeatureResponse> | null;
};

/**
 * APIResponse[list[PlanResponse]]
 */
export type ApiResponseListPlanResponse = {
  /**
   * Success
   */
  success?: boolean;
  /**
   * Status Code
   */
  status_code?: number;
  /**
   * Message
   */
  message?: string;
  /**
   * Data
   */
  data?: Array<PlanResponse> | null;
};

/**
 * APIResponse[list[SubscriptionResponse]]
 */
export type ApiResponseListSubscriptionResponse = {
  /**
   * Success
   */
  success?: boolean;
  /**
   * Status Code
   */
  status_code?: number;
  /**
   * Message
   */
  message?: string;
  /**
   * Data
   */
  data?: Array<SubscriptionResponse> | null;
};

/**
 * APIResponse[list[UsageResponse]]
 */
export type ApiResponseListUsageResponse = {
  /**
   * Success
   */
  success?: boolean;
  /**
   * Status Code
   */
  status_code?: number;
  /**
   * Message
   */
  message?: string;
  /**
   * Data
   */
  data?: Array<UsageResponse> | null;
};

/**
 * APIResponse[list[UserResponse]]
 */
export type ApiResponseListUserResponse = {
  /**
   * Success
   */
  success?: boolean;
  /**
   * Status Code
   */
  status_code?: number;
  /**
   * Message
   */
  message?: string;
  /**
   * Data
   */
  data?: Array<UserResponse> | null;
};

/**
 * Body_upload_file
 */
export type BodyUploadFile = {
  /**
   * File
   */
  file: Blob | File;
};

/**
 * CursorPaginatedTransactions
 */
export type CursorPaginatedTransactions = {
  /**
   * Items
   */
  items: Array<TransactionResponse>;
  /**
   * Next Cursor
   */
  next_cursor?: number | null;
  /**
   * Has More
   */
  has_more: boolean;
};

/**
 * FeatureCreate
 */
export type FeatureCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Code
   */
  code: string;
  /**
   * Unit Price
   */
  unit_price: number | string;
  /**
   * Max Unit Limit
   */
  max_unit_limit: number;
  /**
   * Is Active
   */
  is_active?: boolean;
};

/**
 * FeatureResponse
 */
export type FeatureResponse = {
  /**
   * Name
   */
  name: string;
  /**
   * Code
   */
  code: string;
  /**
   * Unit Price
   */
  unit_price: string;
  /**
   * Max Unit Limit
   */
  max_unit_limit: number;
  /**
   * Is Active
   */
  is_active?: boolean;
  /**
   * Id
   */
  id: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * PlanCreate
 */
export type PlanCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Monthly Fee
   *
   * The recurring monthly price charged for this plan
   */
  monthly_fee: number;
  /**
   * Feature Ids
   *
   * List of feature IDs associated with this plan
   */
  feature_ids?: Array<number>;
};

/**
 * PlanResponse
 */
export type PlanResponse = {
  /**
   * Name
   */
  name: string;
  /**
   * Monthly Fee
   *
   * The recurring monthly price charged for this plan
   */
  monthly_fee: number;
  /**
   * Id
   */
  id: number;
  /**
   * Features
   */
  features?: Array<FeatureResponse>;
};

/**
 * SubscriptionCreate
 */
export type SubscriptionCreate = {
  /**
   * Plan Id
   *
   * ID of the plan to subscribe to
   */
  plan_id: number;
};

/**
 * SubscriptionResponse
 */
export type SubscriptionResponse = {
  /**
   * Id
   */
  id: number;
  /**
   * User Id
   */
  user_id: number;
  /**
   * Plan Id
   */
  plan_id: number;
  /**
   * Billing Day
   */
  billing_day: number;
  /**
   * Last Billing Date
   */
  last_billing_date?: string | null;
  /**
   * Is Active
   */
  is_active: boolean;
  plan: PlanResponse;
};

/**
 * SubscriptionUpdate
 */
export type SubscriptionUpdate = {
  /**
   * Plan Id
   *
   * Change subscription to a new plan ID
   */
  plan_id: number;
  /**
   * Billing Day
   *
   * Update recurring billing day (1-28)
   */
  billing_day?: number | null;
  /**
   * Last Billing Date
   */
  last_billing_date?: string | null;
};

/**
 * Token
 */
export type Token = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Token Type
   */
  token_type?: string;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
  token: Token;
  user: UserResponse;
};

/**
 * TransactionResponse
 */
export type TransactionResponse = {
  /**
   * Id
   */
  id: number;
  /**
   * User Id
   */
  user_id: number;
  /**
   * Subscription Id
   */
  subscription_id: number;
  /**
   * Base Price
   */
  base_price: string;
  /**
   * Extra Charges
   */
  extra_charges: string;
  /**
   * Is Recurring
   */
  is_recurring: boolean;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Total Amount
   */
  readonly total_amount: string;
};

/**
 * UploadResponse
 */
export type UploadResponse = {
  /**
   * Url
   */
  url: string;
};

/**
 * UsageCreate
 */
export type UsageCreate = {
  /**
   * Subscription Id
   *
   * ID of the active subscription being used
   */
  subscription_id: number;
  /**
   * Feature Id
   *
   * ID of the feature feature being consumed
   */
  feature_id: number;
  /**
   * Units Used
   *
   * Number of units consumed (must be greater than 0)
   */
  units_used: number;
};

/**
 * UsageResponse
 */
export type UsageResponse = {
  /**
   * Id
   */
  id: number;
  /**
   * Subscription Id
   */
  subscription_id: number;
  /**
   * Feature Id
   */
  feature_id: number;
  /**
   * Units Used
   */
  units_used: number;
  feature?: FeatureResponse | null;
};

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Email
   */
  email: string;
  role?: UserRole;
  /**
   * Password
   */
  password: string;
  /**
   * Profile Img
   */
  profile_img?: string | null;
};

/**
 * UserLogin
 */
export type UserLogin = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
};

/**
 * UserResponse
 */
export type UserResponse = {
  /**
   * Name
   */
  name: string;
  /**
   * Email
   */
  email: string;
  role?: UserRole;
  /**
   * Id
   */
  id: number;
  /**
   * Profile Img
   */
  profile_img?: string | null;
};

/**
 * UserRole
 */
export type UserRole = "admin" | "buyer";

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

/**
 * APIResponse[CursorPaginatedTransactions]
 */
export type ApiResponseCursorPaginatedTransactionsWritable = {
  /**
   * Success
   */
  success?: boolean;
  /**
   * Status Code
   */
  status_code?: number;
  /**
   * Message
   */
  message?: string;
  data?: CursorPaginatedTransactionsWritable | null;
};

/**
 * CursorPaginatedTransactions
 */
export type CursorPaginatedTransactionsWritable = {
  /**
   * Items
   */
  items: Array<TransactionResponseWritable>;
  /**
   * Next Cursor
   */
  next_cursor?: number | null;
  /**
   * Has More
   */
  has_more: boolean;
};

/**
 * TransactionResponse
 */
export type TransactionResponseWritable = {
  /**
   * Id
   */
  id: number;
  /**
   * User Id
   */
  user_id: number;
  /**
   * Subscription Id
   */
  subscription_id: number;
  /**
   * Base Price
   */
  base_price: string;
  /**
   * Extra Charges
   */
  extra_charges: string;
  /**
   * Is Recurring
   */
  is_recurring: boolean;
  /**
   * Created At
   */
  created_at: string;
};

export type CreateUserData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: "/api/v1/users/create";
};

export type CreateUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type LoginUserData = {
  body: UserLogin;
  path?: never;
  query?: never;
  url: "/api/v1/users/login";
};

export type LoginUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginUserError = LoginUserErrors[keyof LoginUserErrors];

export type LoginUserResponses = {
  /**
   * Successful Response
   */
  200: TokenResponse;
};

export type LoginUserResponse = LoginUserResponses[keyof LoginUserResponses];

export type GetAllUsersData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Role
     */
    role?: string | null;
  };
  url: "/api/v1/users/";
};

export type GetAllUsersErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetAllUsersError = GetAllUsersErrors[keyof GetAllUsersErrors];

export type GetAllUsersResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseListUserResponse;
};

export type GetAllUsersResponse =
  GetAllUsersResponses[keyof GetAllUsersResponses];

export type UploadFileData = {
  body: BodyUploadFile;
  path?: never;
  query?: never;
  url: "/api/v1/storage/upload";
};

export type UploadFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UploadFileError = UploadFileErrors[keyof UploadFileErrors];

export type UploadFileResponses = {
  /**
   * Successful Response
   */
  200: UploadResponse;
};

export type UploadFileResponse = UploadFileResponses[keyof UploadFileResponses];

export type GetFeaturesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/features/";
};

export type GetFeaturesResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseListFeatureResponse;
};

export type GetFeaturesResponse =
  GetFeaturesResponses[keyof GetFeaturesResponses];

export type CreateFeatureData = {
  body: FeatureCreate;
  path?: never;
  query?: never;
  url: "/api/v1/features/";
};

export type CreateFeatureErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateFeatureError = CreateFeatureErrors[keyof CreateFeatureErrors];

export type CreateFeatureResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseFeatureResponse;
};

export type CreateFeatureResponse =
  CreateFeatureResponses[keyof CreateFeatureResponses];

export type GetPlansData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/plans/";
};

export type GetPlansResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseListPlanResponse;
};

export type GetPlansResponse = GetPlansResponses[keyof GetPlansResponses];

export type CreatePlanData = {
  body: PlanCreate;
  path?: never;
  query?: never;
  url: "/api/v1/plans/create";
};

export type CreatePlanErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreatePlanError = CreatePlanErrors[keyof CreatePlanErrors];

export type CreatePlanResponses = {
  /**
   * Successful Response
   */
  201: ApiResponsePlanResponse;
};

export type CreatePlanResponse = CreatePlanResponses[keyof CreatePlanResponses];

export type GetMyTransactionsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Cursor
     *
     * Last seen transaction ID for next page
     */
    cursor?: number | null;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/v1/transaction/me";
};

export type GetMyTransactionsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetMyTransactionsError =
  GetMyTransactionsErrors[keyof GetMyTransactionsErrors];

export type GetMyTransactionsResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseCursorPaginatedTransactions;
};

export type GetMyTransactionsResponse =
  GetMyTransactionsResponses[keyof GetMyTransactionsResponses];

export type GetAllTransactionsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * User Id
     *
     * Filter by user ID
     */
    user_id?: number | null;
    /**
     * Subscription Id
     *
     * Filter by subscription ID
     */
    subscription_id?: number | null;
    /**
     * Cursor
     *
     * Last seen transaction ID for next page
     */
    cursor?: number | null;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/v1/transaction/";
};

export type GetAllTransactionsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetAllTransactionsError =
  GetAllTransactionsErrors[keyof GetAllTransactionsErrors];

export type GetAllTransactionsResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseCursorPaginatedTransactions;
};

export type GetAllTransactionsResponse =
  GetAllTransactionsResponses[keyof GetAllTransactionsResponses];

export type CreateSubscriptionData = {
  body: SubscriptionCreate;
  path?: never;
  query?: never;
  url: "/api/v1/subscription/";
};

export type CreateSubscriptionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateSubscriptionError =
  CreateSubscriptionErrors[keyof CreateSubscriptionErrors];

export type CreateSubscriptionResponses = {
  /**
   * Successful Response
   */
  201: ApiResponseSubscriptionResponse;
};

export type CreateSubscriptionResponse =
  CreateSubscriptionResponses[keyof CreateSubscriptionResponses];

export type GetSubscriptionUsageData = {
  body?: never;
  path: {
    /**
     * Subscription Id
     */
    subscription_id: number;
  };
  query?: never;
  url: "/api/v1/subscription/{subscription_id}/usage";
};

export type GetSubscriptionUsageErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetSubscriptionUsageError =
  GetSubscriptionUsageErrors[keyof GetSubscriptionUsageErrors];

export type GetSubscriptionUsageResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseListUsageResponse;
};

export type GetSubscriptionUsageResponse =
  GetSubscriptionUsageResponses[keyof GetSubscriptionUsageResponses];

export type CancelSubscriptionData = {
  body?: never;
  path: {
    /**
     * Subscription Id
     */
    subscription_id: number;
  };
  query?: never;
  url: "/api/v1/subscription/{subscription_id}";
};

export type CancelSubscriptionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CancelSubscriptionError =
  CancelSubscriptionErrors[keyof CancelSubscriptionErrors];

export type CancelSubscriptionResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseSubscriptionResponse;
};

export type CancelSubscriptionResponse =
  CancelSubscriptionResponses[keyof CancelSubscriptionResponses];

export type UpdateSubscriptionData = {
  body: SubscriptionUpdate;
  path: {
    /**
     * Subscription Id
     */
    subscription_id: number;
  };
  query?: never;
  url: "/api/v1/subscription/{subscription_id}";
};

export type UpdateSubscriptionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateSubscriptionError =
  UpdateSubscriptionErrors[keyof UpdateSubscriptionErrors];

export type UpdateSubscriptionResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseSubscriptionResponse;
};

export type UpdateSubscriptionResponse =
  UpdateSubscriptionResponses[keyof UpdateSubscriptionResponses];

export type GetMySubscriptionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/subscription/me";
};

export type GetMySubscriptionsResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseListSubscriptionResponse;
};

export type GetMySubscriptionsResponse =
  GetMySubscriptionsResponses[keyof GetMySubscriptionsResponses];

export type GetSubscriptionsByUserData = {
  body?: never;
  path: {
    /**
     * User Id
     */
    user_id: number;
  };
  query?: never;
  url: "/api/v1/subscription/user/{user_id}";
};

export type GetSubscriptionsByUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetSubscriptionsByUserError =
  GetSubscriptionsByUserErrors[keyof GetSubscriptionsByUserErrors];

export type GetSubscriptionsByUserResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseListSubscriptionResponse;
};

export type GetSubscriptionsByUserResponse =
  GetSubscriptionsByUserResponses[keyof GetSubscriptionsByUserResponses];

export type CreateUsageData = {
  body: UsageCreate;
  path?: never;
  query?: never;
  url: "/api/v1/usage/";
};

export type CreateUsageErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateUsageError = CreateUsageErrors[keyof CreateUsageErrors];

export type CreateUsageResponses = {
  /**
   * Successful Response
   */
  201: ApiResponseUsageResponse;
};

export type CreateUsageResponse =
  CreateUsageResponses[keyof CreateUsageResponses];

export type GetUserUsageData = {
  body?: never;
  path: {
    /**
     * User Id
     */
    user_id: number;
  };
  query?: never;
  url: "/api/v1/usage/user/{user_id}";
};

export type GetUserUsageErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetUserUsageError = GetUserUsageErrors[keyof GetUserUsageErrors];

export type GetUserUsageResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseListUsageResponse;
};

export type GetUserUsageResponse =
  GetUserUsageResponses[keyof GetUserUsageResponses];

export type RunBillingCycleData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/billing/run";
};

export type RunBillingCycleResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseDict;
};

export type RunBillingCycleResponse =
  RunBillingCycleResponses[keyof RunBillingCycleResponses];

export type GetHomeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type GetHomeResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};
