// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

/**
 * APIResponse[dict]
 */
export const zApiResponseDict = z.object({
  success: z.boolean().optional().default(true),
  status_code: z.int().optional().default(200),
  message: z.string().optional().default("Operation completed successfully"),
  data: z.record(z.string(), z.unknown()).nullish(),
});

/**
 * Body_upload_file
 */
export const zBodyUploadFile = z.object({
  file: z.string(),
});

/**
 * FeatureCreate
 */
export const zFeatureCreate = z.object({
  name: z.string().min(2).max(255),
  code: z.string().min(2).max(100),
  unit_price: z.union([
    z.number().gt(0),
    z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d{0,2}0*$/),
  ]),
  max_unit_limit: z.int().gt(0),
  is_active: z.boolean().optional().default(true),
});

/**
 * FeatureResponse
 */
export const zFeatureResponse = z.object({
  name: z.string().min(2).max(255),
  code: z.string().min(2).max(100),
  unit_price: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d{0,2}0*$/),
  max_unit_limit: z.int().gt(0),
  is_active: z.boolean().optional().default(true),
  id: z.int(),
});

/**
 * APIResponse[FeatureResponse]
 */
export const zApiResponseFeatureResponse = z.object({
  success: z.boolean().optional().default(true),
  status_code: z.int().optional().default(200),
  message: z.string().optional().default("Operation completed successfully"),
  data: zFeatureResponse.nullish(),
});

/**
 * APIResponse[list[FeatureResponse]]
 */
export const zApiResponseListFeatureResponse = z.object({
  success: z.boolean().optional().default(true),
  status_code: z.int().optional().default(200),
  message: z.string().optional().default("Operation completed successfully"),
  data: z.array(zFeatureResponse).nullish(),
});

/**
 * PlanCreate
 */
export const zPlanCreate = z.object({
  name: z.string().min(3).max(50),
  monthly_fee: z.number().gte(0),
  feature_ids: z.array(z.int()).optional(),
});

/**
 * PlanResponse
 */
export const zPlanResponse = z.object({
  name: z.string().min(3).max(50),
  monthly_fee: z.number().gte(0),
  id: z.int(),
  features: z.array(zFeatureResponse).optional(),
});

/**
 * APIResponse[PlanResponse]
 */
export const zApiResponsePlanResponse = z.object({
  success: z.boolean().optional().default(true),
  status_code: z.int().optional().default(200),
  message: z.string().optional().default("Operation completed successfully"),
  data: zPlanResponse.nullish(),
});

/**
 * APIResponse[list[PlanResponse]]
 */
export const zApiResponseListPlanResponse = z.object({
  success: z.boolean().optional().default(true),
  status_code: z.int().optional().default(200),
  message: z.string().optional().default("Operation completed successfully"),
  data: z.array(zPlanResponse).nullish(),
});

/**
 * SubscriptionCreate
 */
export const zSubscriptionCreate = z.object({
  plan_id: z.int(),
});

/**
 * SubscriptionResponse
 */
export const zSubscriptionResponse = z.object({
  id: z.int(),
  user_id: z.int(),
  plan_id: z.int(),
  billing_day: z.int(),
  last_billing_date: z.iso.date().nullish(),
  is_active: z.boolean(),
  plan: zPlanResponse,
});

/**
 * APIResponse[SubscriptionResponse]
 */
export const zApiResponseSubscriptionResponse = z.object({
  success: z.boolean().optional().default(true),
  status_code: z.int().optional().default(200),
  message: z.string().optional().default("Operation completed successfully"),
  data: zSubscriptionResponse.nullish(),
});

/**
 * APIResponse[list[SubscriptionResponse]]
 */
export const zApiResponseListSubscriptionResponse = z.object({
  success: z.boolean().optional().default(true),
  status_code: z.int().optional().default(200),
  message: z.string().optional().default("Operation completed successfully"),
  data: z.array(zSubscriptionResponse).nullish(),
});

/**
 * SubscriptionUpdate
 */
export const zSubscriptionUpdate = z.object({
  plan_id: z.int(),
  billing_day: z.int().gte(1).lte(28).nullish(),
  last_billing_date: z.iso.date().nullish(),
});

/**
 * Token
 */
export const zToken = z.object({
  access_token: z.string(),
  token_type: z.string().optional().default("bearer"),
});

/**
 * TransactionResponse
 */
export const zTransactionResponse = z.object({
  id: z.int(),
  user_id: z.int(),
  subscription_id: z.int(),
  base_price: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
  extra_charges: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
  is_recurring: z.boolean(),
  created_at: z.iso.datetime(),
  total_amount: z
    .string()
    .regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    .readonly(),
});

/**
 * CursorPaginatedTransactions
 */
export const zCursorPaginatedTransactions = z.object({
  items: z.array(zTransactionResponse),
  next_cursor: z.int().nullish(),
  has_more: z.boolean(),
});

/**
 * APIResponse[CursorPaginatedTransactions]
 */
export const zApiResponseCursorPaginatedTransactions = z.object({
  success: z.boolean().optional().default(true),
  status_code: z.int().optional().default(200),
  message: z.string().optional().default("Operation completed successfully"),
  data: zCursorPaginatedTransactions.nullish(),
});

/**
 * UploadResponse
 */
export const zUploadResponse = z.object({
  url: z.string(),
});

/**
 * UsageCreate
 */
export const zUsageCreate = z.object({
  subscription_id: z.int(),
  feature_id: z.int(),
  units_used: z.int().gt(0),
});

/**
 * UsageResponse
 */
export const zUsageResponse = z.object({
  id: z.int(),
  subscription_id: z.int(),
  feature_id: z.int(),
  units_used: z.int(),
  feature: zFeatureResponse.nullish(),
});

/**
 * APIResponse[UsageResponse]
 */
export const zApiResponseUsageResponse = z.object({
  success: z.boolean().optional().default(true),
  status_code: z.int().optional().default(200),
  message: z.string().optional().default("Operation completed successfully"),
  data: zUsageResponse.nullish(),
});

/**
 * APIResponse[list[UsageResponse]]
 */
export const zApiResponseListUsageResponse = z.object({
  success: z.boolean().optional().default(true),
  status_code: z.int().optional().default(200),
  message: z.string().optional().default("Operation completed successfully"),
  data: z.array(zUsageResponse).nullish(),
});

/**
 * UserLogin
 */
export const zUserLogin = z.object({
  email: z.email(),
  password: z.string().min(5),
});

/**
 * UserRole
 */
export const zUserRole = z.enum(["admin", "buyer"]);

/**
 * UserCreate
 */
export const zUserCreate = z.object({
  name: z.string().min(3).max(20),
  email: z.email(),
  role: zUserRole.optional().default("buyer"),
  password: z.string().min(5),
  profile_img: z.string().nullish(),
});

/**
 * UserResponse
 */
export const zUserResponse = z.object({
  name: z.string().min(3).max(20),
  email: z.email(),
  role: zUserRole.optional().default("buyer"),
  id: z.int(),
  profile_img: z.string().nullish(),
});

/**
 * APIResponse[list[UserResponse]]
 */
export const zApiResponseListUserResponse = z.object({
  success: z.boolean().optional().default(true),
  status_code: z.int().optional().default(200),
  message: z.string().optional().default("Operation completed successfully"),
  data: z.array(zUserResponse).nullish(),
});

/**
 * TokenResponse
 */
export const zTokenResponse = z.object({
  token: zToken,
  user: zUserResponse,
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
  loc: z.array(z.union([z.string(), z.int()])),
  msg: z.string(),
  type: z.string(),
  input: z.unknown().optional(),
  ctx: z.record(z.string(), z.unknown()).optional(),
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
  detail: z.array(zValidationError).optional(),
});

/**
 * TransactionResponse
 */
export const zTransactionResponseWritable = z.object({
  id: z.int(),
  user_id: z.int(),
  subscription_id: z.int(),
  base_price: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
  extra_charges: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
  is_recurring: z.boolean(),
  created_at: z.iso.datetime(),
});

/**
 * CursorPaginatedTransactions
 */
export const zCursorPaginatedTransactionsWritable = z.object({
  items: z.array(zTransactionResponseWritable),
  next_cursor: z.int().nullish(),
  has_more: z.boolean(),
});

/**
 * APIResponse[CursorPaginatedTransactions]
 */
export const zApiResponseCursorPaginatedTransactionsWritable = z.object({
  success: z.boolean().optional().default(true),
  status_code: z.int().optional().default(200),
  message: z.string().optional().default("Operation completed successfully"),
  data: zCursorPaginatedTransactionsWritable.nullish(),
});

export const zCreateUserBody = zUserCreate;

/**
 * Successful Response
 */
export const zCreateUserResponse = zUserResponse;

export const zLoginUserBody = zUserLogin;

/**
 * Successful Response
 */
export const zLoginUserResponse = zTokenResponse;

export const zGetAllUsersQuery = z.object({
  role: z.string().nullish(),
});

/**
 * Successful Response
 */
export const zGetAllUsersResponse = zApiResponseListUserResponse;

export const zUploadFileBody = zBodyUploadFile;

/**
 * Successful Response
 */
export const zUploadFileResponse = zUploadResponse;

/**
 * Successful Response
 */
export const zGetFeaturesResponse = zApiResponseListFeatureResponse;

export const zCreateFeatureBody = zFeatureCreate;

/**
 * Successful Response
 */
export const zCreateFeatureResponse = zApiResponseFeatureResponse;

/**
 * Successful Response
 */
export const zGetPlansResponse = zApiResponseListPlanResponse;

export const zCreatePlanBody = zPlanCreate;

/**
 * Successful Response
 */
export const zCreatePlanResponse = zApiResponsePlanResponse;

export const zGetMyTransactionsQuery = z.object({
  cursor: z.int().nullish(),
  limit: z.int().gte(1).lte(100).optional().default(50),
});

/**
 * Successful Response
 */
export const zGetMyTransactionsResponse =
  zApiResponseCursorPaginatedTransactions;

export const zGetAllTransactionsQuery = z.object({
  user_id: z.int().nullish(),
  subscription_id: z.int().nullish(),
  cursor: z.int().nullish(),
  limit: z.int().gte(1).lte(100).optional().default(50),
});

/**
 * Successful Response
 */
export const zGetAllTransactionsResponse =
  zApiResponseCursorPaginatedTransactions;

export const zCreateSubscriptionBody = zSubscriptionCreate;

/**
 * Successful Response
 */
export const zCreateSubscriptionResponse = zApiResponseSubscriptionResponse;

export const zGetSubscriptionUsagePath = z.object({
  subscription_id: z.int(),
});

/**
 * Successful Response
 */
export const zGetSubscriptionUsageResponse = zApiResponseListUsageResponse;

export const zCancelSubscriptionPath = z.object({
  subscription_id: z.int(),
});

/**
 * Successful Response
 */
export const zCancelSubscriptionResponse = zApiResponseSubscriptionResponse;

export const zUpdateSubscriptionBody = zSubscriptionUpdate;

export const zUpdateSubscriptionPath = z.object({
  subscription_id: z.int(),
});

/**
 * Successful Response
 */
export const zUpdateSubscriptionResponse = zApiResponseSubscriptionResponse;

/**
 * Successful Response
 */
export const zGetMySubscriptionsResponse = zApiResponseListSubscriptionResponse;

export const zGetSubscriptionsByUserPath = z.object({
  user_id: z.int(),
});

/**
 * Successful Response
 */
export const zGetSubscriptionsByUserResponse =
  zApiResponseListSubscriptionResponse;

export const zCreateUsageBody = zUsageCreate;

/**
 * Successful Response
 */
export const zCreateUsageResponse = zApiResponseUsageResponse;

export const zGetUserUsagePath = z.object({
  user_id: z.int(),
});

/**
 * Successful Response
 */
export const zGetUserUsageResponse = zApiResponseListUsageResponse;

/**
 * Successful Response
 */
export const zRunBillingCycleResponse = zApiResponseDict;
