"""add subscribtion date, some relational changes

Revision ID: f866e3e2becb
Revises: de3288b1cf86
Create Date: 2026-07-28 17:22:36.693453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f866e3e2becb'
down_revision: Union[str, Sequence[str], None] = 'de3288b1cf86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscribed_at', sa.Date(), nullable=True))

    with op.batch_alter_table('usages', schema=None) as batch_op:
        batch_op.drop_column('recorded_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recorded_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('subscribed_at')

    # ### end Alembic commands ###
